### ISSUE TITLE
Preserve Hi.Res Fix settings

### ISSUE THREAD

**Issue by Ancanus** [Zyin055/Config-Presets#19]
It looks like the settings for Hi.Res Fix are not persisted. Can this be supported too?
![image](https://user-images.githubusercontent.com/487030/216753228-e4d4767a-a921-407f-9517-8466eb1fb036.png)

**Comment by Zyin055** [comment]
Hires. fix, Upscale by, and Denoising strength are tracked by the extension. The Upscaler setting is not because that's dependent on the type of images you're creating (if you always use the same upscaler just set it in `ui-config.json: "txt2img/Upscaler/value"`), and the Resize width/height to are kinda obsolete with the Upscale by setting.

**Comment by Ancanus** [comment]
Thanks! Closing as by design.
