### ISSUE TITLE
[Bug]: Selecting a style with prompt longer than 75 characters results in RuntimeError: The expanded size of the tensor (77) must match the existing size (154) at non-singleton dimension 0. Target sizes: [77, 768]. Tensor sizes: [154, 768]

### ISSUE THREAD

**Issue by Ancanus** [Zyin055/Config-Presets#20]
Selecting a Style that has either a positive or negative prompt longer than 75 characters results in the following error:
`RuntimeError: The expanded size of the tensor (77) must match the existing size (154) at non-singleton dimension 0. Target sizes: [77, 768]. Tensor sizes: [154, 768]`

![image](https://user-images.githubusercontent.com/487030/217113198-3112c660-16fc-4c47-b182-48289b31885b.png)

As a workaround, you have to click the `Apply select styles to the prompt button`

This only happens if you load a Config Preset first. If you don't load a Config Preset, the Style will work as expected.

**Comment by Zyin055** [comment]
I'm unable to reproduce this issue on my end on Automatic1111 commit [226d840e84c5f306350b0681945989b86760e616](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/226d840e84c5f306350b0681945989b86760e616) (Feb 1).

The Config Presets extension doesn't touch anything related to the styles widget, and I don't see how one could cause the other to error. Your issue is most likely a conflict with something else, or a bug within A1111.

**Comment by Ancanus** [comment]
I'll take a closer look.
Closing as NotRepro.
