### ISSUE TITLE
Presets for XYZ-plot don't work

### ISSUE THREAD

**Issue by GlebIgorevich** [Zyin055/Config-Presets#47]
I have presets for XYZ-plot with samplers and steps. It worked correctly.
In the actual version of WebUI this extension does not work correctly: fields X/Y/Z type is filled via presets, but X/Y/Z values not filling and are kept empty. No any error message in the console.

• version: v1.3.2
• python: 3.10.6
• torch: 2.0.1+cu118
• xformers: N/A
• gradio: 3.32.0
• checkpoint: 099e07547a
• Config-Presets f91c65b5

**Comment by Zyin055** [comment]
XYZ Sampler uses a multi-choice dropdown component, which is currently not supported.

**Comment by Manniala** [comment]
Hey, are we able to save the values from XYZ now?
The image on the start page, i see you have XYZ, but when i load the extension i get (image)
![image](https://github.com/Zyin055/Config-Presets/assets/32381860/1ce7075e-ebba-40a1-93c5-ded3951b5260)

**Comment by Zyin055** [comment]
@Manniala you need to add them as a custom field using the button, and editing the text file.

**Comment by Manniala** [comment]
> @Manniala you need to add them as a custom field using the button, and editing the text file.

Ty, but now the next problem is, it does save this now:
"script_txt2img_xyz_plot_x_type": 11,
"script_txt2img_xyz_plot_y_type": 0,
"script_txt2img_xyz_plot_z_type": 0,
"script_txt2img_xyz_plot_x_values": "",
"script_txt2img_xyz_plot_y_values": "",
"script_txt2img_xyz_plot_z_values": ""

But, the values for the "Checkpoint name" are empty, and i just tried to just put in the value "cyberrealistic_v40.safetensors [481d75ae9d]" in the config file, but that leads to it the whole UI not starting

And putting in the "481d75ae9d", the UI could start, but nothing either.
`"script_txt2img_xyz_plot_x_values": "481d75ae9d",`

So that it all looks like this
![image](https://github.com/Zyin055/Config-Presets/assets/32381860/6fe016d5-aeea-4c9c-ae69-d8110c5bb992)

**Comment by Zyin055** [comment]
The XYZ "Checkpoint name" is a multi-choice dropdown component, which is currently not supported.

**Comment by Manniala** [comment]
Ah thought it was now, just found the extension today, and saw the image on the front page, and thought that it may be now :)
That also explains, that it worked when i put in the seed.

And thx for your time, and extension :)
