### ISSUE TITLE
Config Preset UI no longer visible in SD.Next

### ISSUE THREAD

**Issue by brknsoul** [Zyin055/Config-Presets#50]
The latest commit of [SD.Next](https://github.com/vladmandic/automatic/commit/875d0db1038cfecf445cf26a58a678590906e6c8) makes Config Preset's UI no longer visible under the image previewer.

Apparently the cause of this is being anchored to the row of buttons that display after an image is generated (Show, Save, Zip, Delete, etc).

These buttons aren't displayed until an image is generated.

Suggest anchoring elsewhere.

**Comment by Zyin055** [comment]
I don't use Vlad's fork so there is no guarantee that this extension will be compatible with it.

The dropdown needs to be created after all the other fields so that it has access to them in memory, so there's not really a better place to anchor the dropdown. I tried anchoring it to `txt2img_results` and `txt2img_gallery_container` but they aren't actually components that can be anchored to, just HTML elements.

**Comment by brknsoul** [comment]
Vlad recommended a logical place (but may require restructuring the UI) would be under Styles.

**Comment by Zyin055** [comment]
That area of the UI is constructed before all the other components so it wouldn't work.

**Comment by vladmandic** [comment]
ideally, you can create extension ui as independent component and then "rehost" it using js code by simply appending it to any node. that way you can anchor your ui to any number of configurable options. there are extensions that work that way, for example agent scheduler adds enqueue section right there.

**Comment by Neverdusk** [comment]
I'm on the UX branch and I can't see this extension either, for some reason. Even after generating an image.

**Comment by brknsoul** [comment]
Workaround for SD.Next

Edit or create `user.css` in root folder, and add

`#txt2img_footer, #img2img_footer { display: flex; }`

This will force the connected UI element to be displayed upon start up (and not wait until a generation starts).

**Comment by steto123** [comment]
I found the following error in sd.next:

[ERROR][Config Presets] The txt2img component 'txt2img_enable_hr' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at E:\sd.next\automatic\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.

As a result config preset ui is not visible

**Comment by brknsoul** [comment]
https://github.com/Zyin055/Config-Presets/issues/52
