### ISSUE TITLE
[SD.Next] 'txt2img_enable_hr' could not be processed.

### ISSUE THREAD

**Issue by Zyin055** [Zyin055/Config-Presets#53]
I found the following error in sd.next:

[ERROR][Config Presets] The txt2img component 'txt2img_enable_hr' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at E:\sd.next\automatic\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.

As a result config preset ui is not visible

_Originally posted by @steto123 in https://github.com/Zyin055/Config-Presets/issues/50#issuecomment-1656528178_

**Comment by brknsoul** [comment]
Workaround https://github.com/Zyin055/Config-Presets/issues/52

**Comment by Zyin055** [comment]
As I said in the other thread, I do not guarantee compatibility with Vlad's SD.Next because I do not use it. Sounds like Vlad removed the Hires fix checkbox (or renamed the ID), possibly due to trying to support SDXL's refiner model?

If someone wants to submit a PR to either give support for this somehow, or figure out a way to ignore fields that Config Presets cannot find (I couldn't figure out an easy way to do it when I made the extension months ago) then feel free.

**Comment by brknsoul** [comment]
I've popped an Extension Issue up on SD.Next's github, however Vlad's on a vacation for a month from the 27th or 28th of July. He'll still have his laptop and internet access, but that's only for emergencies.

The work-around I linked to above probably could be rolled into a pull request, detecting if one is using SD.Next (rather than A1111) and reference the element IDs correctly, but I'm not a dev, so I'm not sure how to do that.

**Comment by Symbiomatrix** [comment]
@Zyin055 I'm just starting to make sense of vlad's latest, but it seems that at least in principle, it should be possible to make certain components optional, so that if they don't exist in some particular version (ie component is null) then they're simply dropped before the ui build. The PR I've sent seems to be functional both on my old may and latest august versions of vlad's. Could use much more testing however.
If this works, theoretically might also be able to map the same id to multiple components at runtime (depending on which one exists), instead of for example the text replacement for controlnet's mod_radio -> mode_radio correction (backwards compatibility and whatnot).
What do you think?

**Comment by Zyin055** [comment]
@steto123 @brknsoul
This should hopefully be resolved now after merging PR #55 . If it is let me know and I'll close this issue.

**Comment by brknsoul** [comment]
Works perfectly! Thank you for working on this.
