### ISSUE TITLE
UI elements don't show up in 1.6

### ISSUE THREAD

**Issue by nykwil** [Zyin055/Config-Presets#58]
That area under the preview has changed and the config ui doesn't show up anymore.

**Comment by kakaxixx** [comment]
same

**Comment by MrBaralgin** [comment]
Same problem

**Comment by possibleimprobable** [comment]
also experiencing this

**Comment by Zyin055** [comment]
Automatic1111 1.6.0 changed a bunch of stuff. Working on fixes for it.

**Comment by ZincStoat** [comment]
If it's any help the errors I saw go by on load were

[ERROR][Config Presets] The txt2img component 'txt2img_restore_faces' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at C:\Users\windo\stable-diffusion-webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
[ERROR][Config Presets] The img2img component 'img2img_restore_faces' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, or you included a component ID in the custom tracked components config file that does not exist, no longer exists (if you updated an extension), or is an invalid component (if this is the case, you need to manually edit the config file at C:\Users\windo\stable-diffusion-webui\extensions\Config-Presets\config-img2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.

Thanks, and I hope you manage to get things sorted. It looks like a bunch of extensions have been knocked sideways by the update, and yours is one I find especially helpful.

**Comment by Zyin055** [comment]
Please see if the most recent update fixed the issue for 1.6.0.

**Comment by ZincStoat** [comment]
> Please see if the most recent update fixed the issue for 1.6.0.

Looks like that's done it. First I got ...
[ERROR][Config Presets] The txt2img component 'txt2img_tiling' could not be processed. This may be because you are running an outdated version of the Config-Presets extension, you included a component ID in the custom tracked components config file that does not exist, it no longer exists (if you updated an extension or Automatic1111), or is an invalid component (if this is the case, you need to manually edit the config file at C:\Users\windo\stable-diffusion-webui\extensions\Config-Presets\config-txt2img-custom-tracked-components.txt or just delete it so it resets to defaults). This extension will not work until this issue is resolved.
... so I removed the custom-tracked-components files as directed, restarted the UI which regenerated them and I've got my Config Presets back!
Weird thing was, neither restore_faces nor imgtiling were selected in either one, but I'm not going to argue.
Many thanks for the update.

**Comment by ZincStoat** [comment]
I spoke too soon. The UI element is back, but none of the saved configs populate the relevant fields. Am I going to have to set them up again?

**Comment by ZincStoat** [comment]
Ah, I misread that, and hence my earlier search didn't find it. txt2img_tiling is still a default element in custom-tracked-components (as is img2img_tiling), as I discovered after uncommenting the elements I'd had set up before. Looks like that's no longer a thing.

**Comment by UltraBlackLinux** [comment]
Hmm I can still reproduce that all this time later. I just cannot for the life of me find the controls

Edit: Seems to be working now  - I'm not complaining
