### ISSUE TITLE
_js and fn is not a race condition issue

### ISSUE THREAD

**Issue by Gerschel** [Zyin055/Config-Presets#8]
![image](https://user-images.githubusercontent.com/9631031/208220592-5181e573-4b27-4f49-8188-137f629b2328.png)
https://www.gradio.app/custom_CSS_and_JS/

**Comment by Zyin055** [comment]
I've read that piece of documentation before during development. It runs the _js function first, then the python function. That's why I put 2 separate change() methods on config_preset_dropdown, so python runs first, then js. But that didn't work as expected, which is why I called it a race condition and added the 200ms delay to _js since we need the _js to run after the python.
